### ISSUE TITLE
Screen sync quad

### ISSUE THREAD

**Issue by RoboDoig** [neurogears/vestibular-vr#57]
Need to implement a method of synchronising screen updates, as well as visual halts with everything else (HARP ONIX)

Proposed solution is to use a flickering quad somewhere in the corner of the screen with a photodiode recording. The parameters of this flicker (e.g. color) should be changed during halt periods so we can recover both the screen update as well as the timing of each halt.

**Comment by ederancz** [comment]
## There are 2 subtasks. 

### A. the recording the photodiode signal via ONIX analogue input.
1kHz sampling rate should be enough (but we should test in action) 

### B. to signal the stimulus parameter. 
In one small square at the bottom of one of the screens via bonvision. 
We need 3 states as follows:
1. Idle (no vis stimulus) - middle grey 
2. Moving stimulus on (both open- and closed-loop modes) - white
3. Halt - black

**Comment by RoboDoig** [comment]
Regarding A) - this should be taken care of by the existing insertion workflow. We can't connect to the same ONIX board on the main workflow while the insertion workflow is running. I think this should already be essentially implemented since the insertion workflow is logging analogue data and is synchronised with HARP.

**Comment by EleonoraAmbrad** [comment]
@RoboDoig you are right, however, as we will not only use Main workflow with Insertion Workflow but also with the photometry setup, we could add an analog IO node in Main as well. We anyway need to create another one for the photometry to implement synchronisation signal (https://github.com/neurogears/vestibular-vr/issues/56).

**Comment by RoboDoig** [comment]
OK I see, so in the photometry version of the experiment, everything is contained in the Main workflow? No second insertion workflow running?

I've made a PR that should produce the desired screen behavior for recording with the photodiode. It should be possible to inspect that this works visually - see PR #62

**Comment by EleonoraAmbrad** [comment]
I tested the workflow, here are some of my remarks:

- I can position the quad in a good place for the photodiode to detect it, so that's good! The quad is mirrored on the neighbouring screen due to the VR mapping, but it shouldn't be a big deal.

- the halts are applied correctly when setting a halt probability >0 in the yml, but the quad does not change colour upon halt. Before TrialLogic start, the quad is grey (as displayed by the bonsai visualiser values). When the TrialLogic starts (using shift + space), the quad turns white. However, when a halt is applied to the VR, the quad does not change colour. This happens in both DrumClosedLoop and in LinearClosedLoop block

- I could not record the signal of the photodiode because there is no analogIN node yet, but I wasn't sure if that's on purpose (when using Main in combination with InsertionWorkflow in the future, I guess we can record the quad signal using the analog node already present in that workflow, as you suggested)

**Comment by RoboDoig** [comment]
Hi @EleonoraAmbrad, thanks for your feedback!

I will look into the colour not changing on halt, if the colour is changing for the other conditions it probably just means I forgot to update the colour switch somewhere in the halt condition, or assigned the wrong colour.

I didn't implement the ONIX stuff in this PR yet, this will be added in the photometry sync PR which I am working on finishing today. For now it can be recorded with a separate workflow if needed.

**Comment by RoboDoig** [comment]
I've updated the PR, the event that updated the halt color was indeed in the wrong place, should be working now!

**Comment by EleonoraAmbrad** [comment]
the quad changes colour as expected! I think it works perfectly well. 

One small comment: because the start of the logging and the start of the trial logic are controlled via two different key down combinations, and can therefore never be precise enough, we will use the change in colour from grey to white to indicate trial logic start and white to grey to indicate trial logic end. I don't think there should be any problem doing this, right?

PS I also did not record the analog signal yet, I wasn't sure if it is implemented in this PR.

**Comment by RoboDoig** [comment]
Closed with #67
